### ISSUE TITLE
Improve login flow

### ISSUE THREAD

**Issue by mrkvon** [hnuti-brontosaurus/bis-frontend#187]
@lamanchy requested improvements of login and logout flow:

> 1. při návštěvě /login vždy zavolat /logout na backend. Stane se, že backend už je odhlášený a pak se tam člověk nedostane, protože frontend mu ukáže login. Zatím jsem tam měl "hack", že backend tě přesměrovat na logout, ale ten zas nepřeposílá "next" parameter atd, dává to větší smysl takto ;)
>
> 2. psal si, že next parameter může začínat jen /admin/, nebo že je tam nějaké omezení. Můžeš to zrušit? Dělám teď na /game_book/ (sborník her pro BIS), a umím si představit, že přihlášení do BIS budou chtít využít na poszadí i další aplikace (zpěná vazba), jako takový identity provider. Nebo nevím jak to funguje, ale případně tomu aspoň udělat nějaký výpis, proč se to odmítá přesměrovat a kde to změnit. (nebo jen aktuálně aspoň přidat "/game_book", ať to můžu používat a můžem to testovat
>
> A ještě mě tak napadá, pokud to není moc práce, tak by mohl být next i u logout - abych mohl zobrazit vlastní stránku po odhlášení a nezobrazil se mi frontend? Když to budete mít v ruce, ale není to třeba

Keeping track so we don't forget

**Comment by lamanchy** [comment]
Díky! ;⁠-⁠)

**Comment by mrkvon** [comment]
@lamanchy 

In #197 we've added the parameter `next` to `/logout`, and another parameter `reload` to both `/login` and `/logout`.

The `next` specifies the path (or full url) to redirect to. If you provide `reload` parameter, the app will perform an unprotected hard redirect to an arbitrary url, otherwise it will stay within the app.
The protected redirect to `/admin` will still work even without the `reload`.

So you can visit, for example,

https://dev.bis.lomic.cz/logout?next=https%3A%2F%2Fexample.com%2F&reload

and it will sign you out and redirect to https://example.com/

This has a potential to expose users to phishing attacks, or some other attacks, if someone crafts a special url that would lead to a fake site. So, this could be improved by providing whitelist of allowed redirect domains, or by allowing redirect only within the current domain (if we get information that it would be sufficient)

Unfortunately, logging out before login breaks the frontend application functionality, so we would prefer not to provide that feature. Would it be sufficient for you @lamanchy to keep using the "hack", now that `/logout` has the `next` and `reload` options?

If this doesn't satisfy your needs, please let us know and reopen this.
